version: '3.1'

services:

  db:
    image: postgres
    container_name: mountain
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: dbmounth
      PGDATA: /caramba/postgres/data
      POSTGRES_INITB_ARGS: "-A md5"
    ports:
      - "54321:5432"
