# Generated by Django 4.1.4 on 2023-01-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Горный Хребет')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='MountainPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('alt_title', models.CharField(max_length=150, null=True, verbose_name='Альтернативное название')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('images', models.FileField(blank=True, upload_to='files/', verbose_name='Фото')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('status', models.CharField(
                    choices=[('new', 'Новый'), ('pending', 'В работе'), ('accepted', 'Модерация прошла успешно'),
                             ('rejected', 'Отклонено')], default='new', max_length=200, verbose_name='Статус')),
                ('winter', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'),
                                                                 ('3А', '3А'), ('3Б', '3Б')], max_length=2,
                                            verbose_name='Уровень сложности зимой')),
                ('summer', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'),
                                                                 ('3А', '3А'), ('3Б', '3Б')], max_length=2,
                                            verbose_name='Уровень сложности летом')),
                ('autumn', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'),
                                                                 ('3А', '3А'), ('3Б', '3Б')], max_length=2,
                                            verbose_name='Уровень сложности осенью')),
                ('spring', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'),
                                                                 ('3А', '3А'), ('3Б', '3Б')], max_length=2,
                                            verbose_name='Уровень сложности весной')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.area',
                                           verbose_name='Горный хребет')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
